services:
  node:
    build: .
    image: lemmy-daily-games-bot:latest
    environment:
      - LOGIN_INSTANCE_NAME=${LOGIN_INSTANCE_NAME}
      - POST_INSTANCE_NAME=${POST_INSTANCE_NAME}
      - COMMUNITY_NAME=${COMMUNITY_NAME}
      - BOT_USERNAME=${BOT_USERNAME}
      - PASSWORD=${PASSWORD}
      - FEDERATION=${FEDERATION}
      - TIMEZONE=${TIMEZONE}
      - CRON_EXPRESSION=${CRON_EXPRESSION}
      - FORCE_DEFAULT_CRON=${FORCE_DEFAULT_CRON}
      - PUPPETEER_DISABLE_SANDBOX=${PUPPETEER_DISABLE_SANDBOX}
    volumes:
      # - ${ENV_FILE:?Env file not provided}:/usr/src/app/.env
      - ./logs:/usr/src/app/logs
